# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell

    - name: Build go server
      uses: cedrickring/golang-action/go1.12@1.5.2
      with:
        args: go build main/photos_server_run.go -o photos_server
      env:
        GO111MODULE: "on"
        PROJECT_PATH: "./src"

   # - name: Build go server
        #   run: |
        #cd src/main
        #go build -o photos_server
        #ls -l
      #cd ../../

      # Runs a set of commands using the runners shell
    - name: Build front
      run: |
        ls -Rl
        echo Install and build app,
        cd resources
        npm install
        npm run-script build
        tar -cvzf build.tar.gz build

    # Upload artifact
    - uses: actions/upload-artifact@v1
      with:
        name: Artifact front
        path: resources/build.tar.gz
