# Workflow to build at each commit in master the application

name: CI build photos app

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build the back
    - name: Build go server
      run: |
        echo Run build server go
        cd src/main
        export GOOS=linux
        export GOARCH=arm
        go build -o photos_server
        cd ../../
        mkdir artifacts
        echo Copy server artifact in artifacts/
        mv src/main/photos_server artifacts

      # Build the front
    - name: Build front
      run: |
        echo Install and build app,
        cd resources
        npm install
        ls -l /home/runner/work/photos_server/photos_server/resources/node_modules/moment/src/lib
        ls /home/runner/work/photos_server/photos_server/resources/node_modules/moment/lib/locale
        npm run-script build
        tar -cvzf build.tar.gz build
        mv build.tar.gz ../artifacts
      env:
        CI: false

    # Upload artifact
    - uses: actions/upload-artifact@v1
      with:
        name: Artifacts photos server
        path: artifacts
